/*
 * Copyright (c) 2024 MPI-M, Clara Bayley
 *
 * ----- CLEO -----
 * File: createsupers.hpp
 * Project: runcleo
 * Created Date: Tuesday 17th October 2023
 * Author: Clara Bayley (CB)
 * Additional Contributors:
 * -----
 * License: BSD 3-Clause "New" or "Revised" License
 * https://opensource.org/licenses/BSD-3-Clause
 * -----
 * File Description:
 * classes and templated functions required by RunCLEO to create a view of superdroplets
 * (on device) using some initial conditions
 */

#ifndef LIBS_RUNCLEO_CREATESUPERS_HPP_
#define LIBS_RUNCLEO_CREATESUPERS_HPP_

#include <Kokkos_Core.hpp>
#include <Kokkos_Profiling_ScopedRegion.hpp>
#include <algorithm>
#include <limits>
#include <iostream>
#include <stdexcept>
#include <string>

#include "../cleoconstants.hpp"
#include "../kokkosaliases.hpp"
#include "gridboxes/gridboxmaps.hpp"
#include "gridboxes/supersindomain.hpp"
#include "runcleo/gensuperdrop.hpp"

/**
 * @brief Return an initialised view of superdrops in device memory.
 *
 * This function initialises a view of superdrops in device memory by creating
 * a view on the device and copying a host mirror view that is initialised using
 * the `SuperdropInitConds` instance.
 *
 * @tparam SuperdropInitConds The type of the super-droplets' initial conditions data.
 * @param sdic The instance of the super-droplets' initial conditions data.
 * @return A view of superdrops in device memory.
 */
template <typename SuperdropInitConds>
viewd_supers initialise_supers(const SuperdropInitConds& sdic);

/**
 * @brief Rewrite each superdroplet's gridbox index from global to rank-local.
 *
 * The initial conditions describe the whole domain and number gridboxes
 * globally, and every rank reads the same file. Without this step a rank keeps
 * whichever superdroplets happen to have a global index below its LOCAL gridbox
 * count -- with two ranks that is the same first half of the domain on both, so
 * one rank holds droplets it does not own and the other is missing its own.
 * Nothing downstream detects it: sdgbxindex values above the local count look
 * exactly like "this droplet belongs to another rank", so sendrecv_supers
 * decodes a target process from a global gridbox index and gets nonsense.
 *
 * Droplets this rank does not own are marked out of bounds; SupersInDomain then
 * sorts them to the tail of the view, where they cost nothing but the space.
 * For a single rank global and local indexes coincide and this is the identity.
 */
template <GridboxMaps GbxMaps>
void localise_sdgbxindexes(const viewd_supers totsupers, const GbxMaps& gbxmaps) {
  const auto& decomposition = gbxmaps.get_domain_decomposition();
  auto h_totsupers = Kokkos::create_mirror_view_and_copy(Kokkos::HostSpace(), totsupers);

  size_t local = 0;
  for (size_t kk = 0; kk < h_totsupers.extent(0); ++kk) {
    const auto global_index = h_totsupers(kk).get_sdgbxindex();
    if (global_index == LIMITVALUES::oob_gbxindex) continue;

    const auto local_index = decomposition.global_to_local_gridbox_index(global_index);
    if (local_index < 0) {
      h_totsupers(kk).set_sdgbxindex(LIMITVALUES::oob_gbxindex);
    } else {
      h_totsupers(kk).set_sdgbxindex(static_cast<unsigned int>(local_index));
      ++local;
    }
  }

  Kokkos::deep_copy(totsupers, h_totsupers);
  std::cout << "localised " << local << " of " << h_totsupers.extent(0)
            << " superdroplets onto this rank\n";
}

/**
 * @brief Return a mirror view of superdrops on host memory.
 *
 * This function initialises a mirror view of superdrops on host memory, using the super-droplet
 * generator instance `GenSuperdrop` to generate the kk'th super-droplet with their initial Gridbox
 * index, spatial coordinates, and attributes. Kokkos::parallel_for is used to perform parallel
 * initialisation of the mirror view, where each superdrop is generated by the provided `gen`
 * function object.
 *
 * The equivalent serial version of the Kokkos::parallel_for([...]) is:
 * @code
 * for (size_t kk(0); kk < ntotsupers; ++kk)
 * {
 *  h_totsupers(kk) = gen(kk);
 * }
 * @endcode
 *
 * @param sdic The instance of the super-droplets' initial conditions data.
 * @param totsupers The view of superdrops on device memory.
 * @return A mirror view of superdrops on host memory.
 */
template <typename SuperdropInitConds>
viewd_supers::HostMirror initialise_supers_on_host(const SuperdropInitConds& sdic,
                                                   const viewd_supers totsupers);

/**
 * @brief Check if superdroplets initialisation is complete.
 *
 * This function checks if the initialisation of supers view is complete by checking if the
 * superdroplets are sorted by ascending gridbox indexes. If the initialisation is incomplete
 * (the superdroplets are not sorted), it throws an exception with an appropriate error message.
 *
 * @param allsupers Struct to handle all the super-droplets in device memory.
 *
 * @throws std::invalid_argument If the initialisation is incomplete i.e. the super-droplets
 * are not ordered correctly.
 */
void is_sdsinit_complete(const SupersInDomain allsupers);

/**
 * @brief Print statement about initialised super-droplets.
 *
 * This function prints information about each superdroplet, including its ID, Gridbox index,
 * spatial coordinates, and attributes.
 *
 * @param totsupers The view of super-droplets in device memory.
 */
void print_supers(const viewd_constsupers totsupers);

/**
 * @brief Create a view of super-droplets in (device) memory.
 *
 * This function creates an ordered view of superdrops in device memory, where the number
 * of superdrops is specified by the parameter `ntotsupers`. The superdrops are
 * ordered by the gridbox indexes and generated using a generator which uses
 * the initial conditions provided by the `SuperdropInitConds` type.
 *
 * Kokkos::Profiling are null pointers unless a Kokkos profiler library has been
 * exported to "KOKKOS_TOOLS_LIBS" prior to runtime so the lib gets dynamically loaded.
 *
 * @tparam SuperdropInitConds The type of the super-droplets' initial conditions data.
 * @param sdic The instance of the super-droplets' initial conditions data.
 * @param gbxindex_max max value for superdroplet gridbox indexes (0 <= sdgbxindex < gbxindex)
 * @return Struct for handling super-droplets in device memory.
 */
template <typename SuperdropInitConds>
SupersInDomain create_supers(const SuperdropInitConds& sdic, const unsigned int gbxindex_max) {
  Kokkos::Profiling::ScopedRegion region("init_supers");

  // Log message and create superdrops using the initial conditions
  std::cout << "\n--- create superdrops ---\ninitialising\n";
  auto totsupers = initialise_supers(sdic);

  // Log message and sort the view of superdrops
  std::cout << "sorting and finding superdrops in domain\n";
  auto allsupers = SupersInDomain(totsupers, gbxindex_max);

#ifndef NDEBUG

  // Log message and perform checks on the initialisation of superdrops
  std::cout << "checking initialisation\n";
  is_sdsinit_complete(allsupers);

  // Print information about the created superdrops
  print_supers(totsupers);

#endif

  // Log message indicating the successful creation of superdrops
  std::cout << "--- create superdrops: success ---\n";

  return allsupers;
}

/**
 * @brief Build this rank's superdroplets, in a view sized for them rather than for
 * the whole domain.
 *
 * The initial conditions describe the whole domain and say nothing about which rank
 * owns what, so every rank has to read all of it -- but only on the host, and only
 * while this runs. What it keeps is a device view holding the superdroplets in this
 * rank's gridboxes, their indexes translated out of the file's global numbering,
 * plus room for ones that migrate in later.
 *
 * Sizing the view globally instead, which is what happens if you allocate
 * sdic.get_maxnsupers() on every rank, costs more than the memory: the MPI exchange
 * stages the occupied part of the view through the host every motion step, and a
 * view that is comm_size times larger than the superdroplets in it carries that
 * whole factor into the sort as well.
 *
 * capacity_factor is the room for migration, as a multiple of what the rank starts
 * with. It is capped at the global count, so on a single rank this allocates exactly
 * what the unsplit version did and the translation is the identity.
 *
 * @param sdic The super-droplets' initial conditions.
 * @param gbxmaps The gridbox maps, for the domain decomposition.
 * @param capacity_factor View size as a multiple of this rank's initial superdroplets.
 * @return View of superdrops in device memory.
 */
template <typename SuperdropInitConds, GridboxMaps GbxMaps>
viewd_supers initialise_local_supers(const SuperdropInitConds& sdic, const GbxMaps& gbxmaps,
                                     const double capacity_factor) {
  const size_t ntotsupers = sdic.get_maxnsupers();

  auto h_supers = Kokkos::View<Superdrop *, HostSpace>("h_supers", ntotsupers);
  const GenSuperdrop gen(sdic);
  Kokkos::parallel_for("initialise_supers_on_host", Kokkos::RangePolicy<HostSpace>(0, ntotsupers),
                       [=](const size_t kk) { h_supers(kk) = gen(kk); });

  /* Keep the superdroplets in this rank's gridboxes, compacted to the front. A
  droplet whose global index is not in this partition is simply dropped -- another
  rank is keeping it. */
  const auto &decomposition = gbxmaps.get_domain_decomposition();
  size_t n_local = 0;
  for (size_t kk = 0; kk < ntotsupers; ++kk) {
    const auto global_index = h_supers(kk).get_sdgbxindex();
    if (global_index == LIMITVALUES::oob_gbxindex) continue;

    const auto local_index = decomposition.global_to_local_gridbox_index(global_index);
    if (local_index < 0) continue;

    h_supers(n_local) = h_supers(kk);
    h_supers(n_local).set_sdgbxindex(static_cast<unsigned int>(local_index));
    ++n_local;
  }

  const auto wanted = static_cast<size_t>(static_cast<double>(n_local) * capacity_factor);
  const size_t capacity = std::min(ntotsupers, std::max(n_local, wanted));
  for (size_t kk = n_local; kk < capacity; ++kk) {
    h_supers(kk).set_sdgbxindex(LIMITVALUES::oob_gbxindex);
  }

  auto totsupers =
      viewd_supers(Kokkos::view_alloc("totsupers", Kokkos::WithoutInitializing), capacity);
  Kokkos::deep_copy(totsupers, Kokkos::subview(h_supers, Kokkos::make_pair(size_t{0}, capacity)));

  std::cout << "rank holds " << n_local << " of " << ntotsupers << " superdroplets; view sized "
            << capacity << " (" << capacity_factor << "x) for migration\n";

  return totsupers;
}

/**
 * @brief As above, but taking the gridbox maps so the superdroplets' gridbox
 * indexes can be converted from the global numbering used by the initial
 * conditions to this rank's local one first.
 *
 * Use this whenever the run may be decomposed across more than one rank; the
 * overload taking a bare gbxindex_max cannot tell a global index apart from a
 * local one and silently keeps the wrong droplets. See localise_sdgbxindexes.
 */
template <typename SuperdropInitConds, GridboxMaps GbxMaps>
SupersInDomain create_supers(const SuperdropInitConds& sdic, const GbxMaps& gbxmaps,
                             const double capacity_factor = 1.5) {
  Kokkos::Profiling::ScopedRegion region("init_supers");

  std::cout << "\n--- create superdrops ---\ninitialising\n";
  auto totsupers = initialise_local_supers(sdic, gbxmaps, capacity_factor);

  std::cout << "sorting and finding superdrops in domain\n";
  auto allsupers = SupersInDomain(totsupers, gbxmaps.get_local_ngridboxes_hostcopy());

#ifndef NDEBUG
  std::cout << "checking initialisation\n";
  is_sdsinit_complete(allsupers);
  print_supers(totsupers);
#endif

  std::cout << "--- create superdrops: success ---\n";

  return allsupers;
}

/**
 * @brief Return an initialised view of superdrops in device memory.
 *
 * This function initialises a view of superdrops in device memory by creating
 * a view on the device and copying a host mirror view that is initialised using
 * the `SuperdropInitConds` instance.
 *
 * @tparam SuperdropInitConds The type of the super-droplets' initial conditions data.
 * @param sdic The instance of the super-droplets' initial conditions data.
 * @return A view of superdrops in device memory.
 */
template <typename SuperdropInitConds>
viewd_supers initialise_supers(const SuperdropInitConds& sdic) {
  // create superdrops view on device
  auto totsupers = viewd_supers("totsupers", sdic.get_maxnsupers());

  // initialise a mirror of superdrops view on host
  auto h_totsupers = initialise_supers_on_host(sdic, totsupers);

  // Copy host view to device (h_totsupers to totsupers)
  Kokkos::deep_copy(totsupers, h_totsupers);

  return totsupers;
}

/**
 * @brief Return a mirror view of superdrops on host memory.
 *
 * This function initialises a mirror view of superdrops on host memory, using the super-droplet
 * generator instance `GenSuperdrop` to generate the kk'th super-droplet with their initial Gridbox
 * index, spatial coordinates, and attributes. Kokkos::parallel_for is used to perform parallel
 * initialisation of the mirror view, where each superdrop is generated by the provided `gen`
 * function object.
 *
 * The equivalent serial version of the Kokkos::parallel_for([...]) is:
 * @code
 * for (size_t kk(0); kk < ntotsupers; ++kk)
 * {
 *  h_totsupers(kk) = gen(kk);
 * }
 * @endcode
 *
 * @param sdic The instance of the super-droplets' initial conditions data.
 * @param totsupers The view of superdrops on device memory.
 * @return A mirror view of superdrops on host memory.
 */
template <typename SuperdropInitConds>
viewd_supers::HostMirror initialise_supers_on_host(const SuperdropInitConds& sdic,
                                                   const viewd_supers totsupers) {
  // Create a mirror view of supers in case the original view is on device memory
  auto h_totsupers = Kokkos::create_mirror_view(totsupers);

  // Parallel initialisation of the mirror view
  const auto ntotsupers = totsupers.extent(0);
  const GenSuperdrop gen(sdic);
  Kokkos::parallel_for("initialise_supers_on_host", Kokkos::RangePolicy<HostSpace>(0, ntotsupers),
                       [=](const size_t kk) { h_totsupers(kk) = gen(kk); });

  return h_totsupers;
}

#endif  // LIBS_RUNCLEO_CREATESUPERS_HPP_
